version: '3'
services:
  jenkins:
    restart: always
    image: shaozeming/jenknis:node
    container_name: jenkins
    volumes:
    - /Users/shaozeming/Tool/jenkins/home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker
    ports:
    - "18080:8080"
    - "5000:5000"
    - "50000:50000"
